/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TraceabilityAnchor {
  export type AnchorRecordStruct = {
    entityId: BytesLike;
    payloadHash: BytesLike;
    entityType: BigNumberish;
    anchoredBy: AddressLike;
    timestamp: BigNumberish;
  };

  export type AnchorRecordStructOutput = [
    entityId: string,
    payloadHash: string,
    entityType: bigint,
    anchoredBy: string,
    timestamp: bigint
  ] & {
    entityId: string;
    payloadHash: string;
    entityType: bigint;
    anchoredBy: string;
    timestamp: bigint;
  };
}

export interface TraceabilityAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchor"
      | "getEntityIds"
      | "getRecord"
      | "owner"
      | "totalAnchored"
      | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Anchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchor",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntityIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAnchored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "anchor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntityIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AnchoredEvent {
  export type InputTuple = [
    entityId: BytesLike,
    payloadHash: BytesLike,
    entityType: BigNumberish,
    anchoredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entityId: string,
    payloadHash: string,
    entityType: bigint,
    anchoredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entityId: string;
    payloadHash: string;
    entityType: bigint;
    anchoredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TraceabilityAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): TraceabilityAnchor;
  waitForDeployment(): Promise<this>;

  interface: TraceabilityAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchor: TypedContractMethod<
    [entityId: BytesLike, payloadHash: BytesLike, entityType: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEntityIds: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getRecord: TypedContractMethod<
    [entityId: BytesLike],
    [TraceabilityAnchor.AnchorRecordStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  totalAnchored: TypedContractMethod<[], [bigint], "view">;

  verify: TypedContractMethod<
    [entityId: BytesLike, payloadHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchor"
  ): TypedContractMethod<
    [entityId: BytesLike, payloadHash: BytesLike, entityType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEntityIds"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [entityId: BytesLike],
    [TraceabilityAnchor.AnchorRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAnchored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [entityId: BytesLike, payloadHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "Anchored"
  ): TypedContractEvent<
    AnchoredEvent.InputTuple,
    AnchoredEvent.OutputTuple,
    AnchoredEvent.OutputObject
  >;

  filters: {
    "Anchored(bytes32,bytes32,uint8,address,uint64)": TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
    Anchored: TypedContractEvent<
      AnchoredEvent.InputTuple,
      AnchoredEvent.OutputTuple,
      AnchoredEvent.OutputObject
    >;
  };
}
